### ISSUE TITLE
Arch Linux game patching crash

### ISSUE THREAD

**Issue by Lojemiru** [AM2R-Community-Developers/AM2RLauncher#1]
Relevant log information:

2021-03-25 20:11:30,567 [1] INFO AM2RLauncher.MainForm - Imported and extracted mod .zip as AM2R.Co-op.1.1.2.Linux
2021-03-25 20:11:30,567 [1] INFO AM2RLauncher.MainForm - AM2R Multitroid AMD VM successfully installed.
2021-03-25 20:11:32,832 [1] INFO AM2RLauncher.MainForm - Loading profiles...
2021-03-25 20:11:32,833 [1] INFO AM2RLauncher.MainForm - Profiles loaded.
2021-03-25 20:11:32,833 [1] INFO AM2RLauncher.MainForm - SettingsProfileDropDown.SelectedIndex has been changed to 2.
2021-03-25 20:11:35,254 [1] INFO AM2RLauncher.MainForm - profileDropDown.SelectedIndex has been changed to 2.
2021-03-25 20:11:35,254 [1] INFO AM2RLauncher.MainForm - SettingsProfileDropDown.SelectedIndex has been changed to 2.
2021-03-25 20:11:35,255 [1] INFO AM2RLauncher.MainForm - SettingsProfileDropDown.SelectedIndex has been changed to 2.
2021-03-25 20:11:36,574 [1] INFO AM2RLauncher.MainForm - SettingsProfileDropDown.SelectedIndex has been changed to 2.
2021-03-25 20:11:36,574 [1] INFO AM2RLauncher.MainForm - SettingsProfileDropDown.SelectedIndex has been changed to 2.
2021-03-25 20:11:36,578 [4] INFO AM2RLauncher.MainForm - Installing profile AM2R Multitroid AMD VM...
2021-03-25 20:11:36,951 [4] INFO AM2RLauncher.MainForm - Profile folder created and AM2R_11.zip extracted.
2021-03-25 20:11:36,970 [4] ERROR AM2RLauncher.MainForm - Could not find file '/home/live/AM2Rtesting/linux64(5)/Profiles/AM2R Multitroid AMD VM/assets/AM2R'.
*****Stack Trace*****

   at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at AM2RLauncher.MainForm.InstallProfile(ProfileXML profile)
   at AM2RLauncher.MainForm.<PlayButtonClickEvent>b__4_1()

![](https://cdn.discordapp.com/attachments/815363835082833941/824752942820491274/aaa-2021-03-25_18.11.02.webm)

![](https://cdn.discordapp.com/attachments/297954856709390336/825248451981869056/unknown.png)

**Comment by Miepee** [comment]
Haven't had any Problems on my Arch machine or other Arch machines, so will close it.
