### ISSUE TITLE
AM2R_Launcher does not run with libwebkit2gtk-5.0

### ISSUE THREAD

**Issue by ImonFyre** [AM2R-Community-Developers/AM2RLauncher#38]
**Describe the bug**
When trying to execute AM2R_Launcher on a system that has libwebkit2gtk-5.0 installed, the application crashes with the following:

```
Unhandled Exception has occured in your Application.
Unable to load shared library 'libwebkit2gtk-4.0.so.37' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/home/kyle/am2r/AM2R_Launcher/libwebkit2gtk-4.0.so.37.so: cannot open shared object file: No such file or directory
/opt/dotnet-sdk-bin-7.0/shared/Microsoft.NETCore.App/7.0.0/libwebkit2gtk-4.0.so.37.so: cannot open shared object file: No such file or directory
/home/kyle/am2r/AM2R_Launcher/liblibwebkit2gtk-4.0.so.37.so: cannot open shared object file: No such file or directory
/opt/dotnet-sdk-bin-7.0/shared/Microsoft.NETCore.App/7.0.0/liblibwebkit2gtk-4.0.so.37.so: cannot open shared object file: No such file or directory
/home/kyle/am2r/AM2R_Launcher/libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory
/opt/dotnet-sdk-bin-7.0/shared/Microsoft.NETCore.App/7.0.0/libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory
/home/kyle/am2r/AM2R_Launcher/liblibwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory
/opt/dotnet-sdk-bin-7.0/shared/Microsoft.NETCore.App/7.0.0/liblibwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory

*****Stack Trace*****

   at Eto.GtkSharp.NativeMethods.NMLinux.webkit_web_view_new()
   at Eto.GtkSharp.NativeMethods.webkit_web_view_new()
   at Eto.GtkSharp.Forms.Controls.WebViewHandler..ctor()
   at Eto.GtkSharp.Platform.<>c.<AddTo>b__12_61()
   at Eto.Widget..ctor()
   at Eto.Forms.BindableWidget..ctor()
   at Eto.Forms.Control..ctor()
   at Eto.Forms.WebView..ctor()
   at AM2RLauncher.MainForm..ctor() in /home/runner/work/AM2RLauncher/AM2RLauncher/AM2RLauncher/AM2RLauncher/MainForm/MainForm.UI.cs:line 324
   at AM2RLauncher.Gtk.MainClass.Main() in /home/runner/work/AM2RLauncher/AM2RLauncher/AM2RLauncher/AM2RLauncher.Gtk/Program.cs:line 79
Check the logs at /root/.local/share/AM2RLauncher for more info!
```

**Expected behavior**
AM2R launcher runs

**To Reproduce**
1.  Install libwebkit2gtk-5.0
2. run AM2R_Launcher
3. 

**Platform**
 - OS: Gentoo Linux, Kernel 6.0.10
 - AM2RLauncher Version:  2.3.0

[AM2RLauncher.log](https://github.com/AM2R-Community-Developers/AM2RLauncher/files/10147487/AM2RLauncher.log)

**Comment by Miepee** [comment]
Eto bug, I noticed the same recently when trying to upgrade the Gnome version on the Flatpak: https://github.com/flathub/io.github.am2r_community_developers.AM2RLauncher/pull/4

Thanks for the reminder to open the issue upstream.

**Comment by Miepee** [comment]
Opened issue upstream: https://github.com/picoe/Eto/issues/2361

**Comment by ImonFyre** [comment]
Awesome, glad I could be helpful in some way /thumbsup
